from yzy_server.database.apis.node import get_node_by_uuid
from yzy_server.database.apis.node import get_node_by_name
from yzy_server.database.apis.node import get_node_by_ip
from yzy_server.database.apis.node import get_nodes_by_uuids
from yzy_server.database.apis.node import get_node_by_pool_uuid
from yzy_server.database.apis.node import get_controller_node
from yzy_server.database.apis.node import get_backup_node
from yzy_server.database.apis.node import add_server_node
from yzy_server.database.apis.node import get_node_with_all
from yzy_server.database.apis.node import get_node_storage_all
from yzy_server.database.apis.node import get_node_storage_first
from yzy_server.database.apis.node import get_node_storage_by_path
from yzy_server.database.apis.node import get_controller_image
from yzy_server.database.apis.node import get_node_with_first
from yzy_server.database.apis.node import get_template_sys_storage
from yzy_server.database.apis.node import get_template_data_storage
from yzy_server.database.apis.node import get_instance_sys_storage
from yzy_server.database.apis.node import get_instance_data_storage
from yzy_server.database.apis.node import get_service_by_node_uuid
from yzy_server.database.apis.node import get_service_by_uuid
from yzy_server.database.apis.node import get_service_by_name
from yzy_server.database.apis.node import get_node_manage_nic_name
from yzy_server.database.apis.node import add_monitor_half_min
from yzy_server.database.apis.node import clear_monitor_half_min
from yzy_server.database.apis.node import select_controller_image_ip
from yzy_server.database.apis.node import add_ha_info
from yzy_server.database.apis.node import get_ha_info_by_uuid
from yzy_server.database.apis.node import get_ha_info_all
from yzy_server.database.apis.node import get_ha_info_first

from yzy_server.database.apis.network import get_default_network
from yzy_server.database.apis.network import get_network_by_uuid
from yzy_server.database.apis.network import get_subnet_by_uuid
from yzy_server.database.apis.network import get_virtual_switch
from yzy_server.database.apis.network import get_default_virtual_switch
from yzy_server.database.apis.network import add_virtual_switch_uplink
from yzy_server.database.apis.network import add_virtual_swtich
from yzy_server.database.apis.network import add_network
from yzy_server.database.apis.network import add_subnet
from yzy_server.database.apis.network import get_virtual_switch_by_name
from yzy_server.database.apis.network import get_network_by_name
from yzy_server.database.apis.network import get_subnet_by_name
from yzy_server.database.apis.network import get_subnet_by_network
from yzy_server.database.apis.network import get_networks
from yzy_server.database.apis.network import get_virtual_switch_list
from yzy_server.database.apis.network import get_uplinks_all
from yzy_server.database.apis.network import get_network_all
from yzy_server.database.apis.network import get_nics_all
from yzy_server.database.apis.network import get_nics_first
from yzy_server.database.apis.network import get_nic_ips_all
from yzy_server.database.apis.network import add_nic_ip
from yzy_server.database.apis.network import get_nic_ip_by_uuid
from yzy_server.database.apis.network import get_nic_ip_by_name
from yzy_server.database.apis.network import get_nic_ip_by_ip
from yzy_server.database.apis.network import get_interface_by_network
from yzy_server.database.apis.network import get_network_by_nic
from yzy_server.database.apis.network import add_nic
from yzy_server.database.apis.network import add_bond_nics
from yzy_server.database.apis.network import get_bond_nics_all
from yzy_server.database.apis.network import get_bond_nics_first
from yzy_server.database.apis.network import get_uplinks_first

from yzy_server.database.apis.desktop import create_instance_template
from yzy_server.database.apis.desktop import get_instance_template
from yzy_server.database.apis.desktop import get_voi_instance_template
from yzy_server.database.apis.desktop import get_voi_devices_with_all
from yzy_server.database.apis.desktop import get_voi_operate_with_all
from yzy_server.database.apis.desktop import get_template_mac
from yzy_server.database.apis.desktop import get_voi_template_mac
from yzy_server.database.apis.desktop import get_instance_mac
from yzy_server.database.apis.desktop import get_template_ipaddr
from yzy_server.database.apis.desktop import get_voi_template_ipaddr
from yzy_server.database.apis.desktop import get_personal_ipaddr
from yzy_server.database.apis.desktop import get_education_ipaddr
from yzy_server.database.apis.desktop import create_group
from yzy_server.database.apis.desktop import create_group_user
from yzy_server.database.apis.desktop import create_desktop
from yzy_server.database.apis.desktop import create_personal_desktop
from yzy_server.database.apis.desktop import create_random_desktop
from yzy_server.database.apis.desktop import create_instance
from yzy_server.database.apis.desktop import create_device
from yzy_server.database.apis.desktop import insert_with_many
from yzy_server.database.apis.desktop import get_desktop_by_uuid
from yzy_server.database.apis.desktop import get_instance_by_desktop
from yzy_server.database.apis.desktop import get_instance_by_desktop_and_node
from yzy_server.database.apis.desktop import get_devices_by_instance
from yzy_server.database.apis.desktop import get_devices_with_first
from yzy_server.database.apis.desktop import get_devices_modify_with_first
from yzy_server.database.apis.desktop import get_devices_with_all
from yzy_server.database.apis.desktop import get_devices_modify_with_all
from yzy_server.database.apis.desktop import get_template_version
from yzy_server.database.apis.desktop import get_template_with_all
from yzy_server.database.apis.desktop import get_voi_template_with_all
from yzy_server.database.apis.desktop import get_voi_template_by_uuids
from yzy_server.database.apis.desktop import get_instance_with_all
from yzy_server.database.apis.desktop import get_instance_all_by_uuids
from yzy_server.database.apis.desktop import get_instance_all_by_terminal_ips
from yzy_server.database.apis.desktop import get_instance_by_desktop_first_alloc
from yzy_server.database.apis.desktop import get_instance_with_first
from yzy_server.database.apis.desktop import get_delete_instance_with_first
from yzy_server.database.apis.desktop import get_desktop_with_all
from yzy_server.database.apis.desktop import get_desktop_with_all_by_uuids
from yzy_server.database.apis.desktop import get_desktop_with_all_by_groups
from yzy_server.database.apis.desktop import get_group_with_first
from yzy_server.database.apis.desktop import get_group_with_all
from yzy_server.database.apis.desktop import get_group_user_with_first
from yzy_server.database.apis.desktop import create_group_user_session
from yzy_server.database.apis.desktop import get_personal_desktop_with_first
from yzy_server.database.apis.desktop import get_personal_desktop_order_by_order_num
from yzy_server.database.apis.desktop import get_desktop_order_by_order_num
from yzy_server.database.apis.desktop import get_personal_desktop_all_by_uuids
from yzy_server.database.apis.desktop import get_random_desktop_with_all
from yzy_server.database.apis.desktop import get_random_desktop_with_first
from yzy_server.database.apis.desktop import get_user_random_instance_with_all
from yzy_server.database.apis.desktop import create_user_random_instance
from yzy_server.database.apis.desktop import get_group_user_with_all
from yzy_server.database.apis.desktop import get_group_user_session_first
from yzy_server.database.apis.desktop import get_personal_desktop_with_all
from yzy_server.database.apis.desktop import get_instance_max_terminal_id
from yzy_server.database.apis.desktop import get_instance_all
from yzy_server.database.apis.desktop import get_terminal_with_all
from yzy_server.database.apis.desktop import get_template_by_uuid_first
from yzy_server.database.apis.desktop import get_instance_first
from yzy_server.database.apis.desktop import get_desktop_with_first
from yzy_server.database.apis.desktop import create_course_many
from yzy_server.database.apis.desktop import create_course_schedule_many
from yzy_server.database.apis.desktop import create_course_template
from yzy_server.database.apis.desktop import get_course_schedule_with_first
from yzy_server.database.apis.desktop import get_course_schedule_with_all
from yzy_server.database.apis.desktop import get_course_template_with_first
from yzy_server.database.apis.desktop import get_course_template_with_all
from yzy_server.database.apis.desktop import get_course_with_all
from yzy_server.database.apis.desktop import get_course_with_first
from yzy_server.database.apis.desktop import get_term_with_first
from yzy_server.database.apis.desktop import get_term_with_all
from yzy_server.database.apis.desktop import create_term
from yzy_server.database.apis.desktop import update_course_schedule_many
from yzy_server.database.apis.desktop import get_distinct_course_template_uuids_by_course_schedule
from yzy_server.database.apis.desktop import get_distinct_course_template_uuids_by_course
from yzy_server.database.apis.desktop import get_distinct_course_schedule_week_nums
from yzy_server.database.apis.desktop import delete_course_schedule_many
from yzy_server.database.apis.desktop import delete_course_template_many_by_uuids
from yzy_server.database.apis.desktop import delete_course_many_by_course_template_uuids

from yzy_server.database.apis.resource_pool import get_resource_pool_list
from yzy_server.database.apis.resource_pool import get_resource_pool_by_key
from yzy_server.database.apis.resource_pool import add_resource_pool
from yzy_server.database.apis.resource_pool import add_task_info
from yzy_server.database.apis.resource_pool import get_task_step
from yzy_server.database.apis.resource_pool import get_task_first
from yzy_server.database.apis.resource_pool import get_image_task_state_first
from yzy_server.database.apis.resource_pool import get_task_all
from yzy_server.database.apis.resource_pool import get_images_with_all
from yzy_server.database.apis.resource_pool import get_image_with_first
from yzy_server.database.apis.resource_pool import get_iso_with_first
from yzy_server.database.apis.resource_pool import get_task_first_with_progress_desc

from yzy_server.database.apis.log import add_operation_log
from yzy_server.database.apis.log import get_operation_log_all

from yzy_server.database.apis.system import create_database_back
from yzy_server.database.apis.system import get_crontab_tasks
from yzy_server.database.apis.system import create_crontab_task
from yzy_server.database.apis.system import get_database_backup_first
from yzy_server.database.apis.system import get_database_backup_all
from yzy_server.database.apis.system import get_crontab_first
from yzy_server.database.apis.system import create_crontab_detail
from yzy_server.database.apis.system import get_crontab_detail_all
from yzy_server.database.apis.system import get_crontab_detail_first
from yzy_server.database.apis.system import get_admin_user_first
from yzy_server.database.apis.system import get_warning_log_all
from yzy_server.database.apis.system import get_operation_log_all
from yzy_server.database.apis.system import get_warn_setup_first
from yzy_server.database.apis.system import create_warn_setup
from yzy_server.database.apis.system import create_task_info
from yzy_server.database.apis.system import get_task_info_first
from yzy_server.database.apis.system import get_task_with_type_all

from yzy_server.database.apis.voi import create_voi_group
from yzy_server.database.apis.voi import create_voi_template
from yzy_server.database.apis.voi import create_voi_desktop
from yzy_server.database.apis.voi import create_template_operate
from yzy_server.database.apis.voi import create_voi_terminal_desktop_bind
from yzy_server.database.apis.voi import update_voi_terminal_desktop_bind
from yzy_server.database.apis.voi import update_voi_terminal_desktop_info
from yzy_server.database.apis.voi import create_voi_terminal_share
from yzy_server.database.apis.voi import create_voi_device
from yzy_server.database.apis.voi import get_item_with_all
from yzy_server.database.apis.voi import get_item_with_first
from yzy_server.database.apis.voi import delete_voi_terminal_desktops

from yzy_server.database.apis.remote_storage import add_remote_storage
from yzy_server.database.apis.remote_storage import get_remote_storage_by_key
from yzy_server.database.apis.remote_storage import update_remote_storage

