# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-08 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='图片')),
            ],
            options={
                'verbose_name': '测试图片上传应用',
                'verbose_name_plural': '测试图片上传应用',
                'db_table': 'tb_fdfs_pic',
            },
        ),
    ]
