# Generated by Django 2.1 on 2020-02-25 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YzyNodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=64, unique=True)),
                ('hostname', models.CharField(max_length=32, unique=True)),
                ('ip', models.GenericIPAddressField(protocol='ipv4')),
                ('total_mem', models.IntegerField(default=0, null=True)),
                ('running_mem', models.IntegerField(default=0, null=True)),
                ('single_reserve_mem', models.IntegerField(default=0, null=True)),
                ('total_vcpus', models.IntegerField(default=0, null=True)),
                ('running_vcpus', models.IntegerField(default=0, null=True)),
                ('server_version_info', models.CharField(max_length=64, null=True)),
                ('graphics_card_info', models.CharField(max_length=64, null=True)),
                ('cpu_info', models.CharField(max_length=64, null=True)),
                ('mem_info', models.CharField(max_length=64, null=True)),
                ('sys_img_uuid', models.UUIDField(null=True)),
                ('data_img_uuid', models.UUIDField(null=True)),
                ('vm_sys_uuid', models.UUIDField(null=True)),
                ('vm_data_uuid', models.UUIDField(null=True)),
                ('status', models.IntegerField(default=0)),
                ('type', models.IntegerField(default=0)),
                ('deleted', models.IntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'yzy_nodes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='YzyResourcePools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('desc', models.CharField(blank=True, max_length=500, null=True)),
                ('default', models.IntegerField(default=0)),
                ('deleted', models.IntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'yzy_resource_pools',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='yzynodes',
            name='resource_pool',
            field=models.ForeignKey(db_column='resource_pool_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yzy_nodes', to='web_manage.YzyResourcePools', to_field='uuid'),
        ),
    ]
