# Generated by Django 2.1 on 2020-02-25 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_manage', '0002_auto_20200225_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='YzyNetworks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('switch_name', models.CharField(max_length=64)),
                ('vlan_id', models.IntegerField(default=200)),
                ('switch_type', models.CharField(default='', max_length=10)),
                ('default', models.IntegerField(default=0)),
                ('deleted', models.IntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'yzy_networks',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='YzyVirtualSwitchs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('desc', models.CharField(max_length=64, null=True)),
                ('type', models.CharField(max_length=10)),
                ('default', models.IntegerField(default=0)),
                ('deleted', models.IntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'yzy_virtual_switch',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='yzynetworks',
            name='switch',
            field=models.ForeignKey(db_column='switch_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yzy_vs_networks', to='web_manage.YzyVirtualSwitchs', to_field='uuid'),
        ),
    ]
