# Generated by Django 2.1 on 2020-02-26 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_manage', '0003_auto_20200225_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='YzyNodeNetworkInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=64, unique=True)),
                ('nic', models.CharField(max_length=32, unique=True)),
                ('mac', models.CharField(max_length=32, unique=True)),
                ('speed', models.IntegerField(null=True)),
                ('ip', models.CharField(max_length=32)),
                ('netmask', models.CharField(max_length=32)),
                ('is_image', models.IntegerField(default=0)),
                ('is_manage', models.IntegerField(default=0)),
                ('type', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('deleted', models.IntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(db_column='node_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yzy_node_networks', to='web_manage.YzyNodes', to_field='uuid')),
            ],
            options={
                'db_table': 'yzy_node_network_info',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='YzyVirtualSwitchUplink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=64, unique=True)),
                ('node_uuid', models.CharField(max_length=64)),
                ('status', models.IntegerField(default=0)),
                ('deleted', models.IntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('network_interface', models.ForeignKey(db_column='nic_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yzy_network_interface_uplinks', to='web_manage.YzyNodeNetworkInfo', to_field='uuid')),
                ('virtual_switch', models.ForeignKey(db_column='vs_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yzy_virtual_switch_uplinks', to='web_manage.YzyVirtualSwitchs', to_field='uuid')),
            ],
            options={
                'db_table': 'yzy_vswitch_uplink',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='yzynetworks',
            name='vlan_id',
            field=models.IntegerField(default=200, null=True),
        ),
    ]
