# Generated by Django 2.1 on 2020-02-26 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_manage', '0004_auto_20200226_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='YzySubnets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('netmask', models.CharField(max_length=64)),
                ('gateway', models.CharField(max_length=64)),
                ('cidr', models.CharField(max_length=64, null=True)),
                ('start_ip', models.CharField(max_length=64, null=True)),
                ('end_ip', models.CharField(max_length=64, null=True)),
                ('dns1', models.CharField(max_length=64, null=True)),
                ('dns2', models.CharField(max_length=64, null=True)),
                ('deleted', models.IntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('network', models.ForeignKey(db_column='network_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yzy_network_subnets', to='web_manage.YzyNetworks', to_field='uuid')),
            ],
            options={
                'db_table': 'yzy_subnets',
                'ordering': ['id'],
            },
        ),
    ]
