# Generated by Django 2.1 on 2020-02-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_manage', '0005_yzysubnets'),
    ]

    operations = [
        migrations.CreateModel(
            name='YzyISO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('md5_sum', models.CharField(max_length=64)),
                ('desc', models.CharField(max_length=64, null=True)),
                ('path', models.CharField(max_length=64)),
                ('type', models.IntegerField(default=0)),
                ('sys_type', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('deleted', models.IntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'yzy_iso',
                'ordering': ['id'],
            },
        ),
    ]
